Update build.yml
Signed-off-by: z33sss <gvkf4rbp4f@privaterelay.appleid.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,17 +4,37 @@ on:
   workflow_dispatch:
 jobs:
   build-arm:
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Install dependencies & aarch64 cross gcc
+      - name: Install dependencies
         run: |
           curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
           sudo apt-get update
-          # Ubuntu22.04(jammy)源存在gcc7交叉编译器
-          sudo apt-get install -y nodejs gcc-7-aarch64-linux-gnu g++-7-aarch64-linux-gnu file
+          sudo apt-get install -y nodejs file
+
+      - name: Cache cross compiler (aarch64)
+        uses: actions/cache@v4
+        with:
+          path: ${{ github.workspace }}/tools/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu
+          key: gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu
+
+      - name: Configure cross compiler (aarch64)
+        run: |
+          mkdir -p $GITHUB_WORKSPACE/tools
+          if [ ! -d "$GITHUB_WORKSPACE/tools/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu" ]; then
+            cd $GITHUB_WORKSPACE/tools
+            # 南阳理工大学 Linaro 镜像
+            wget --no-verbose https://mirror.nyist.edu.cn/linaro-toolchain/binaries/7.5-2019.12/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz
+            if ! file gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz | grep -q "XZ compressed data"; then
+              echo "ERROR: Downloaded file is not a valid tar.xz!"
+              exit 1
+            fi
+            tar -xJf gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz
+          fi
+          echo "PATH=$PATH:$GITHUB_WORKSPACE/tools/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin" >> $GITHUB_ENV
 
       - name: build web
         run: |
@@ -24,11 +44,9 @@ jobs:
       - name: build server
         run: |
           cd src
-          # 打印调试信息确认编译器
-          which aarch64-linux-gnu-gcc-7
-          aarch64-linux-gnu-gcc-7 --version
-          # 如果Makefile默认用aarch64-linux-gnu-gcc，需要指定CC
-          make CC=aarch64-linux-gnu-gcc-7 CXX=aarch64-linux-gnu-g++-7
+          which aarch64-linux-gnu-gcc
+          aarch64-linux-gnu-gcc --version
+          make
 
       - name: dopack
         run: |
